### ISSUE TITLE
2D seismic Проблемы с отрисовкой

### ISSUE THREAD

**Issue by khakhulin** [pathfinder14/OpenSAPM#28]
При использовании модуля для решения 2д задачи рисовалка крушится после составления 2 временного слоя. Предполагается, что проблема в модуле для отрисовки.

**Comment by KESHAmambo** [comment]
Проблема точно в модуле для отрисовки, ошибка вылетает в строке 
`    cs = ax.contourf(solution, levels, cmap=cmap, norm=norm, extend='both')
`

**Comment by s1lya** [comment]
fixed
